### ISSUE TITLE
编译成功 但测试图片没识别出来

### ISSUE THREAD

**Issue by Yaoxingtian** [BaofengZan/yolov5_2.0-TensorRt#4]
您好！感谢开源。
我按照您的步骤编译好的了，但是测试的两张图片并没有正确的检测出图像内容，没有一个检测框出现，请问可以大概定位是什么问题吗，谢谢！

**Comment by BaofengZan** [comment]
你好，请移步https://github.com/wang-xinyu/tensorrt，可以加入readme中的微信群
